apiVersion: v1
kind: Secret
metadata:
    name: test-secret
data:
    username: YWRtaW4=
    password: dGhpc2lzYXRlc3R0aGluZy4=
    the_key: a21neXNhI2Z6KzkoejEqPWMweWRyaml6ayo3c3RobTJnYTF6ND1eNjEkY3hjcThiJGw=