apiVersion: batch/v1
kind: Job
metadata:
  name: django-migration
spec:
  backoffLimit: 5
  template:
    spec:
      containers: 
      - name: django-migration
        image: nyuappsec/assign3:v0
        command: ['python3', 'manage.py', 'migrate']
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: the_key

            - name: ADMIN_UNAME
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: username

            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: password

      restartPolicy: Never
